name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render
        run: |
          curl -I https://im-nu-bot.onrender.com/